# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - so_arm100_controller

  so_arm100_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
      - jaw_joint
